services:
  db_postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    env_file:
      - .env

  bot_service:
    build:
      context: ./users_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
